package rekam_medis;

import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */

public class menu extends javax.swing.JFrame {

    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        boder_kiri = new javax.swing.JPanel();
        boder_kanan = new javax.swing.JPanel();
        boder_bawah = new javax.swing.JPanel();
        boder_atas = new javax.swing.JPanel();
        isi_data_pasien = new javax.swing.JButton();
        isi_data_dokter = new javax.swing.JButton();
        isi_data_obat = new javax.swing.JButton();
        isi_data_periksa = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 890, 10));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REKAM MEDIS RUMAH SAKIT UTY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 600, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jl. Ringroad Utara - Yogyakarta. D.I. 55285");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telp. (0274) 623310, E-mail: info@uty.ac.id, Homepage: www.uty.ac.id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logo-baru-uty-putih2-80x80.png"))); // NOI18N
        logo.setText(" ");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        boder_kiri.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout boder_kiriLayout = new javax.swing.GroupLayout(boder_kiri);
        boder_kiri.setLayout(boder_kiriLayout);
        boder_kiriLayout.setHorizontalGroup(
            boder_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boder_kiriLayout.setVerticalGroup(
            boder_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(boder_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 310));

        boder_kanan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout boder_kananLayout = new javax.swing.GroupLayout(boder_kanan);
        boder_kanan.setLayout(boder_kananLayout);
        boder_kananLayout.setHorizontalGroup(
            boder_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boder_kananLayout.setVerticalGroup(
            boder_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(boder_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 10, 310));

        boder_bawah.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout boder_bawahLayout = new javax.swing.GroupLayout(boder_bawah);
        boder_bawah.setLayout(boder_bawahLayout);
        boder_bawahLayout.setHorizontalGroup(
            boder_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boder_bawahLayout.setVerticalGroup(
            boder_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(boder_bawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 900, 10));

        boder_atas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout boder_atasLayout = new javax.swing.GroupLayout(boder_atas);
        boder_atas.setLayout(boder_atasLayout);
        boder_atasLayout.setHorizontalGroup(
            boder_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boder_atasLayout.setVerticalGroup(
            boder_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(boder_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 10));

        isi_data_pasien.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isi_data_pasien.setText("Isi Data Pasien");
        isi_data_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_data_pasienActionPerformed(evt);
            }
        });
        jPanel1.add(isi_data_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, -1));

        isi_data_dokter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isi_data_dokter.setText("Isi Data Dokter");
        isi_data_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_data_dokterActionPerformed(evt);
            }
        });
        jPanel1.add(isi_data_dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 180, -1));

        isi_data_obat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isi_data_obat.setText("Isi Data Obat");
        isi_data_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_data_obatActionPerformed(evt);
            }
        });
        jPanel1.add(isi_data_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 180, -1));

        isi_data_periksa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isi_data_periksa.setText("Isi Data Periksa");
        isi_data_periksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_data_periksaActionPerformed(evt);
            }
        });
        jPanel1.add(isi_data_periksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 180, -1));

        keluar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isi_data_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_data_pasienActionPerformed
        // TODO add your handling code here:
        new pasien().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_isi_data_pasienActionPerformed

    private void isi_data_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_data_obatActionPerformed
        // TODO add your handling code here:
        new obat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_isi_data_obatActionPerformed

    private void isi_data_periksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_data_periksaActionPerformed
        // TODO add your handling code here:
        new periksa().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_isi_data_periksaActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int keluar = JOptionPane.showConfirmDialog(null,"Apakah Anda  yakin mau keluar?","Question",JOptionPane.YES_NO_OPTION);
        if(keluar==0){
            System.exit(0);
        }else{ 
            return;
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void isi_data_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_data_dokterActionPerformed
        // TODO add your handling code here:
        new dokter().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_isi_data_dokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boder_atas;
    private javax.swing.JPanel boder_bawah;
    private javax.swing.JPanel boder_kanan;
    private javax.swing.JPanel boder_kiri;
    private javax.swing.JButton isi_data_dokter;
    private javax.swing.JButton isi_data_obat;
    private javax.swing.JButton isi_data_pasien;
    private javax.swing.JButton isi_data_periksa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
